# baseURL = "http://example.org/"
baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "BEL Language"
theme = "learn"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
disableLanguageSwitchingButton = true

[params]
# editURL = "https://github.com/belbio/bel_lang_ws/tree/master/content/"
description = "Documentation for BEL Language"
author = "William Hayes"
showVisitedLinks = false
disableBreadcrumb = false
disableNextPrev = false
themeVariant = "bio"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for BEL Language"
weight = 1
languageName = "English"


[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> <label>Contributing</label>"
url = "/2.1.0/contributing"
weight = 25

[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> <label>Credits</label>"
url = "/2.1.0/credits"
weight = 30


[[menu.shortcuts]]
name = "<i class='fa fa-smile'></i> <label>BEL.bio website</label>"
url = "https://bel.bio"
weight = 35
